import {createServer,type Server} from "node:http";import type{ProjectionStore}from"./store.ts";import{buildMarketChart,parseChartRange}from"./chart.ts";import{buildMarketStats}from"./market-stats.ts";import type{PantaCatalogService}from"./provider-catalog.ts";
const json=(res:any,status:number,body:unknown)=>{res.writeHead(status,{"content-type":"application/json","cache-control":"no-store","access-control-allow-origin":"*"});res.end(JSON.stringify(body,(_,v)=>typeof v==="bigint"?v.toString():v))};
const marketTrades=(store:ProjectionStore,marketId:string)=>[...store.events.values()].filter(e=>e.kind==="trade"&&e.marketId===marketId);
const withStats=(store:ProjectionStore,market:any)=>({...market,stats:buildMarketStats(market,store.prices.get(market.address)??[],marketTrades(store,market.marketId),store.portfolios.values())});
export function createIndexerApi(store:ProjectionStore,panta?:PantaCatalogService):Server{return createServer(async(req,res)=>{const url=new URL(req.url??"/","http://localhost");const parts=url.pathname.split("/").filter(Boolean);
 if(url.pathname==="/health")return json(res,200,store.health);
 if(url.pathname==="/v1/providers/panta/status")return panta?json(res,200,panta.status):json(res,503,{error:"panta-not-configured"});
 if(url.pathname==="/v1/providers/panta/markets"){if(!panta)return json(res,503,{error:"panta-not-configured"});try{return json(res,200,await panta.markets({status:url.searchParams.get("status") as any||undefined,category:url.searchParams.get("category")||undefined,query:url.searchParams.get("query")||undefined,limit:Number(url.searchParams.get("limit")||50)}))}catch(error){return json(res,502,{error:"panta-unavailable",message:error instanceof Error?error.message:String(error)})}}
 if(parts[0]==="v1"&&parts[1]==="providers"&&parts[2]==="panta"&&parts[3]==="markets"&&parts[4]){if(!panta)return json(res,503,{error:"panta-not-configured"});try{return json(res,200,await panta.market(parts[4]))}catch(error){return json(res,502,{error:"panta-unavailable",message:error instanceof Error?error.message:String(error)})}}
 if(url.pathname==="/v1/markets")return json(res,200,[...store.markets.values()].map(m=>withStats(store,m)));
 if(parts[0]==="v1"&&parts[1]==="markets"&&parts[2]){const x=store.markets.get(parts[2]);if(!x)return json(res,404,{error:"not-found"});if(parts[3]==="trades")return json(res,200,[...store.events.values()].filter(e=>e.kind==="trade"&&e.marketId===x.marketId).sort((a,b)=>b.slot-a.slot));if(parts[3]==="funding")return json(res,200,[...store.events.values()].filter(e=>e.kind==="funding"&&e.marketId===x.marketId));if(parts[3]==="prices")return json(res,200,store.prices.get(x.address)??[]);if(parts[3]==="chart")return json(res,200,buildMarketChart(store.prices.get(x.address)??[],[...store.events.values()].filter(e=>e.kind==="trade"&&e.marketId===x.marketId),parseChartRange(url.searchParams.get("range"))));return json(res,200,withStats(store,x))}
 if(parts[0]==="v1"&&parts[1]==="owners"&&parts[2]&&parts[3]==="portfolio"){const owner=parts[2].toLowerCase();const x=[...store.portfolios.values()].find(p=>p.owner.toLowerCase()===owner);return x?json(res,200,x):json(res,404,{error:"not-found"})}
 if(parts[0]==="v1"&&parts[1]==="portfolios"&&parts[2]){const x=store.portfolios.get(parts[2]);if(!x)return json(res,404,{error:"not-found"});if(parts[3]==="positions")return json(res,200,x.positions);if(parts[3]==="transactions")return json(res,200,[...store.events.values()].filter(e=>e.portfolio===x.address));return json(res,200,x)}
 if(url.pathname==="/v1/status/oracle")return json(res,200,{lastSlot:store.health.oracleLastSlot,indexedSlot:store.health.indexedSlot});
 if(url.pathname==="/v1/status/keeper")return json(res,200,{lastSlot:store.health.keeperLastSlot,indexedSlot:store.health.indexedSlot});
 if(url.pathname==="/v1/events")return json(res,200,[...store.events.values()].sort((a,b)=>b.slot-a.slot));
 return json(res,404,{error:"not-found"});})}
